<a href="https://colab.research.google.com/github/billybuonocore/Finance/blob/main/William_Buonocore_Stats_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loops

In [1]:
# test loop for random number

In [ ]:
for i in range(10):
  print (i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(5,8):
  print(i)

5
6
7


In [ ]:
for i in range (3):
  print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


In [ ]:
# Functions

In [ ]:
def square (x):
  return x**2

In [ ]:
square (5)

25

In [ ]:
def add_two(x):
  return x+2

In [2]:
# square root and addition

In [ ]:
square(add_two(5))

49

In [ ]:
choice = "apple"

In [ ]:
if choice == "apple":

  print("You choose apples.")

else: 

  print("You did not choose apples.")

You choose apples.


In [3]:
# picking a random item from choice of computer

In [ ]:
if choice == "apple":

  print("You choose apples.")

elif choice == "orange":

    print("You choose oranges.")

else: 

    print("You did not choose apples.")

You choose apples.


# User Input

In [ ]:
choice = input("Please enter your choice(i.e. apple): ")

Please enter your choice(i.e. apple): oranges


In [ ]:
choice

'oranges'

# New

In [4]:
# random generator for deck of cards

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52)

array([35, 40, 22, 39, 44, 17, 12, 34, 49, 13, 32, 16,  0,  4, 48,  2, 38,
       18,  1, 28,  9, 26, 33, 15,  6, 36, 25, 31, 41, 37, 21, 23,  3, 20,
       45, 47, 19, 30, 29, 42, 24, 46,  8, 50, 43, 14, 10, 27, 11, 51,  5,
        7])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards[0]

45

In [ ]:
cards[1]

28

In [5]:
# random card from deck of cards and whole deck showing

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [6]:
# all numbers of cards and suits

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
def card_name(card_number):

  suit = card_number//13
  name = card_number%13

  return names[name] + " of " + suits[suit]

In [ ]:
card_name(0)

'Ace of Clubs'

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck          = card_name(cards[0])
second_card_in_deck  = card_name(cards[1])
last_card_in_deck    =card_name(cards[-1])

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Nine of Diamonds', 'Four of Clubs', 'Six of Clubs')

In [7]:
# random number and suit of a card from deck

In [ ]:
for i in range(5):
  print(card_name(cards[i]))

Nine of Diamonds
Four of Clubs
Three of Spades
Seven of Clubs
Ten of Spades


In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','1']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(1, 0)

In [ ]:
suit[i]

'p'

In [ ]:
card[j]

'a'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [8]:
# card shown in deck

In [ ]:
show_img(img)